
version: '4.32.0'

services:

    redis: 
      image: redis:7.4-rc

    django:
      container_name: django
      build: 
        context: ./djcelery
      command: py manage.py runserver 0.0.0.0:8000
      volumes:
        - ./djcelery:/app/
      ports:
        - 8001:8000
      environment:
        - DEBUG=1
        - SECRET_KEY=082JDFS8848KHW38LF-233
        - ALLOWED_HOSTS=localhost
      depends_on:
        - redis

    celery:
      container_name: celery
      build: 
        context: ./djcelery
      command: celery --app=djcelery worker -l INFO
      volumes:
        - ./djcelery:/app/
      environment:
        - DEBUG=1
        - SECRET_KEY=082JDFS8848KHW38LF-233
        - ALLOWED_HOSTS=localhost
      depends_on:
        - redis