
version: '4.32.0'

services:

    django:
      container_name: django
      build: 
        context: ./djcelery
      command: py manage.py runserver 0.0.0.0:8000
      volumes:
        - ./djcelery:/app/
      ports:
        - 8001:8000
      environment:
        - DEBUG=1
        - SECRET_KEY=082JDFS8848KHW38LF-233
        - ALLOWED_HOSTS=localhost,127.0.0.1